- name: run mysql and webapp docker containers
  hosts: 127.0.0.1
  connection: local

  tasks:

  - name: delete log directory
    file: path={{ log }} state=absent
 
  - name: create log directory
    file: path={{ log }} state=directory

  - name: create configurations directory
    file: path={{ configurations_dest }} state=directory

  - include: download.yml dir=properties name=application.properties

  - include: download.yml dir=properties name=batch.properties

  - include: download.yml dir=json name=restapp.postman_environment.json

  - name: run mysql
    docker_container:
      name: mysqldb
      image: mysql-sample
      ports: "3306:3306"
      env:
        MYSQL_ROOT_PASSWORD: dba
      state: started

  - include: wait.yml image=mysqldb

  - name: run webapp
    docker_container:
      name: webapp
      image: spring-boot-sample
      ports: "8080:8080"
      volumes:
      - "{{ log }}:/var/log"
      - "{{ configurations_dest }}:/properties"
      state: started

  - include: wait.yml image=webapp
